package com.jieoz.lanmediawall.player.net

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Byte-exact alignment tests for canonical JSON + HMAC against reference
 * vectors generated by the *actual* Python implementation
 * (windows_player/envelope.py + broker/envelope.py):
 *
 *   canonical_json = json.dumps(payload, sort_keys=True,
 *                               separators=(",", ":"), ensure_ascii=False)
 *   sig            = HMAC_SHA256(PSK, "{v}|{type}|{msg_id}|{ts}|{from}|{to}|{cj}")
 *
 * If any of these fail, the Android player cannot interoperate with the broker.
 */
class EnvelopeTest {

    private val psk = "CHANGE_ME_32_BYTE_RANDOM_PRESHARED_KEY"

    // --- canonical JSON vectors (from Python) ------------------------

    @Test
    fun canonical_nested_nonAscii_sortedKeys() {
        val payload = jsonObj {
            put("device_name", "\u5927\u5385\u5de6\u5c4f")
            put("screen", jsonObj { put("w", 1920); put("h", 1080) })
            put("capabilities", jsonStrArr(listOf("video", "image")))
            put("group_id", "lobby")
            put("online", true)
            put("volume", 80)
            put("muted", false)
            put("zeta", 1)
            put("alpha", 2)
        }
        val expected =
            "{\"alpha\":2,\"capabilities\":[\"video\",\"image\"],\"device_name\":\"\u5927\u5385\u5de6\u5c4f\",\"group_id\":\"lobby\",\"muted\":false,\"online\":true,\"screen\":{\"h\":1080,\"w\":1920},\"volume\":80,\"zeta\":1}"
        assertEquals(expected, CanonicalJson.encode(payload))
    }

    @Test
    fun canonical_empty_object() {
        assertEquals("{}", CanonicalJson.encode(jsonObj {}))
    }

    @Test
    fun canonical_string_escaping() {
        // a"b\c<newline>d<tab>e/f<U+0001><U+001F><U+4E2D>
        val s = "a\"b\\c\nd\te/f\u0001\u001f\u4e2d"
        val payload = jsonObj { put("s", s) }
        val expected = "{\"s\":\"a\\\"b\\\\c\\nd\\te/f\\u0001\\u001f\u4e2d\"}"
        assertEquals(expected, CanonicalJson.encode(payload))
    }

    @Test
    fun canonical_array_of_objects_and_ints() {
        val payload = jsonObj {
            put("items", jsonArr(listOf(
                jsonObj { put("item_id", "a1"); put("size", 10485760L); put("loop", false) },
                jsonObj { put("item_id", "b2"); put("duration_ms", 60000L) },
            )))
            put("offset", -12)
            put("big", 1750000003000L)
        }
        val expected =
            "{\"big\":1750000003000,\"items\":[{\"item_id\":\"a1\",\"loop\":false,\"size\":10485760},{\"duration_ms\":60000,\"item_id\":\"b2\"}],\"offset\":-12}"
        assertEquals(expected, CanonicalJson.encode(payload))
    }

    // --- HMAC signature vectors (from Python) ------------------------

    @Test
    fun hmac_hello_vector() {
        val payload = jsonObj {
            put("device_name", "\u5927\u5385\u5de6\u5c4f")
            put("screen", jsonObj { put("w", 1920); put("h", 1080) })
            put("capabilities", jsonStrArr(listOf("video", "image")))
            put("group_id", "lobby")
            put("online", true)
            put("volume", 80)
            put("muted", false)
            put("zeta", 1)
            put("alpha", 2)
        }
        val sig = Envelope.sign(psk, 1, "hello", "m1", 1750000000000L,
            "player:and-1", "broker", payload)
        assertEquals("ff509dda6abd9c317cd105be3a3cda52df34fb211751fcd2fab67aafb19dbafd", sig)
    }

    @Test
    fun hmac_empty_payload_vector() {
        val sig = Envelope.sign(psk, 1, "status", "m2", 1750000000123L,
            "player:x", "broker", jsonObj {})
        assertEquals("63e6b289f260366b0008114ed0aecfa96951389f4864198bc1d343e5cb8b6404", sig)
    }

    @Test
    fun hmac_escaping_vector() {
        val payload = jsonObj { put("s", "a\"b\\c\nd\te/f\u0001\u001f\u4e2d") }
        val sig = Envelope.sign(psk, 1, "x", "m3", 42L, "a", "b", payload)
        assertEquals("89efc2eff634df85500b3104044260bb57baa98d9527daeb49bcdb9e31ee64c3", sig)
    }

    @Test
    fun hmac_playat_vector() {
        val payload = jsonObj {
            put("items", jsonArr(listOf(
                jsonObj { put("item_id", "a1"); put("size", 10485760L); put("loop", false) },
                jsonObj { put("item_id", "b2"); put("duration_ms", 60000L) },
            )))
            put("offset", -12)
            put("big", 1750000003000L)
        }
        val sig = Envelope.sign(psk, 1, "play_at", "m4", 1750000003000L,
            "broker", "group:lobby", payload)
        assertEquals("73252a98ff11e70fc70d66ad6932a05e172e621c17e52e66507eed01cbe91e4b", sig)
    }

    // --- round-trip build → verify ------------------------------------

    @Test
    fun build_then_verify_roundtrip() {
        val payload = jsonObj {
            put("device_id", "and-1")
            put("state", "playing")
            put("name", "\u5ba3\u4f20\u7247.mp4")
        }
        val env = Envelope.build(psk, "status", "player:and-1", "broker", payload)
        val wire = Envelope.toWire(env)
        val result = Envelope.verify(psk, wire, firstConnect = true)
        assertTrue(result.ok)
        assertEquals(Envelope.Reason.OK, result.reason)
        assertEquals("status", result.parsed?.type)
        assertEquals("playing", result.parsed?.payloadObj?.entries?.get("state")?.let {
            (it as Json.Str).value
        })
    }

    @Test
    fun verify_rejects_tampered_signature() {
        val payload = jsonObj { put("x", 1) }
        val env = Envelope.build(psk, "x", "a", "b", payload)
        val wire = Envelope.toWire(env).replace("\"x\":1", "\"x\":2")
        val result = Envelope.verify(psk, wire, firstConnect = true)
        assertFalse(result.ok)
        assertEquals(Envelope.Reason.SIG, result.reason)
    }

    @Test
    fun verify_rejects_wrong_psk() {
        val payload = jsonObj { put("x", 1) }
        val env = Envelope.build(psk, "x", "a", "b", payload)
        val result = Envelope.verify("different-key", Envelope.toWire(env), firstConnect = true)
        assertFalse(result.ok)
        assertEquals(Envelope.Reason.SIG, result.reason)
    }

    @Test
    fun verify_rejects_stale_timestamp() {
        val payload = jsonObj { put("x", 1) }
        val env = Envelope.build(psk, "x", "a", "b", payload, ts = 1000L)
        val result = Envelope.verify(psk, Envelope.toWire(env), now = 10_000_000L)
        assertFalse(result.ok)
        assertEquals(Envelope.Reason.STALE, result.reason)
    }

    @Test
    fun verify_dedups_replayed_msg_id() {
        val replay = ReplayCache()
        val payload = jsonObj { put("x", 1) }
        val env = Envelope.build(psk, "x", "a", "b", payload)
        val wire = Envelope.toWire(env)
        val first = Envelope.verify(psk, wire, replay = replay, firstConnect = true)
        val second = Envelope.verify(psk, wire, replay = replay, firstConnect = true)
        assertTrue(first.ok)
        assertFalse(second.ok)
        assertEquals(Envelope.Reason.DUP, second.reason)
    }

    @Test
    fun parse_roundtrip_preserves_integers() {
        val parsed = Json.parse("{\"a\":1750000003000,\"b\":-12,\"c\":0}")
        assertEquals(
            "{\"a\":1750000003000,\"b\":-12,\"c\":0}",
            CanonicalJson.encode(parsed),
        )
    }

    @Test
    fun parse_unicode_escape_decodes() {
        val parsed = Json.parse("{\"s\":\"\\u4e2d\\u6587\"}")
        assertEquals("{\"s\":\"\u4e2d\u6587\"}", CanonicalJson.encode(parsed))
    }
}
